### ISSUE TITLE
Open Shells

### ISSUE THREAD

**Issue by MIWdlB** [UCL-CCS/Nbed#90]
To make the code work for open shelled systems we have to:

- [x] Update CLI to include spin
- [x] Create a flag for restricted/unrestricted in Driver
- [x] Introduce UHF/UKS as an  option where we create scf objects
- [x] Localize each spin separately
- [ ] Create unique projectors for each spin
- [ ] Embed each spin with its own `Vemb`
- [ ] Delete the environment of each spin individually
- [ ] Read in unrestricted scf objects to HamiltonianBuilder.

Additionally to make sure nothing is broken:
- [x] Update existing tests
- [ ] Localizer
- [ ] HamiltonianBuilder
- [ ] Driver

**Comment by m-i-w** [comment]
### hcore -> hcore + Vemb

The current method we have of introducing the projector to hcore doesnt work when we have different Vemb for each spin. There are two ways we could go about fixing this:

1. Change how the `kernel()` function and `energy_elec()` in pyscf works
2. Add Vemb to `get_veff` which does allow for different values for different spins.

After tinkering with it, option 2 seems better. I'll add tests to make sure that nothing else is changed in the output that I haven't thought of.

**Comment by MIWdlB** [comment]
- [ ] Find out how PySCF FCI keeps track of the charge and spin. 

When we solve by diagonalisation we need to choose the right eigenvalue.
